scala_library(
    name = "scalaz-interop",
    dependencies = [
        "core:core",
        "cache:cache",
        "3rdparty/jvm:scalaz-concurrent",
    ],
    sources = rglobs("jvm/*.scala", "shared/*.scala"),
)
