/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sbt_JniLibrary */

#ifndef _Included_sbt_JniLibrary
#define _Included_sbt_JniLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sbt_JniLibrary
 * Method:    getIntegerValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sbt_JniLibrary_getIntegerValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
