#!/bin/sh
# sbt launcher script for Cygwin and MSYS

JAVA_CMD=java
JAVA_OPTS=-Xmx512M

UDIR=`dirname "$0"`
if [ -z "$MSYSTEM" ]; then
  WDIR=`cygpath -alm "$UDIR"`
else
  WDIR=`echo "$UDIR" | sed -e 's~^/\([^/]*\)/~\1:/~'`
fi

if [ "_$TERM" = "_xterm" ]; then
  # Let the terminal handle ANSI sequences
  stty -icanon min 1 -echo > /dev/null 2>&1
  $JAVA_CMD $JAVA_OPTS -Djline.terminal=jline.UnixTerminal -jar "$WDIR/sbt-launch.jar" $@
  stty icanon echo > /dev/null 2>&1
else
  # Use Jansi to intercept ANSI sequences
  $JAVA_CMD $JAVA_OPTS -Dsbt.log.format=true -cp "$WDIR/jansi.jar;$WDIR/sbt-launch.jar;$WDIR/classes" SbtJansiLaunch $@
fi
