name: CI
on:
  pull_request:
  push:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            java: 8
            distribution: adopt
            jobtype: 9
    runs-on: ${{ matrix.os }}
    timeout-minutes: 25
    env:
      JAVA_OPTS: -Xms800M -Xmx2G -Xss6M -XX:ReservedCodeCacheSize=128M -server -Dsbt.io.virtual=false -Dfile.encoding=UTF-8
      JVM_OPTS: -Xms800M -Xmx2G -Xss6M -XX:ReservedCodeCacheSize=128M -server -Dsbt.io.virtual=false -Dfile.encoding=UTF-8
      SCALA_212: 2.12.20
      UTIL_TESTS: "utilCache/test utilControl/test utilInterface/test utilLogging/test utilPosition/test utilRelation/test utilScripted/test utilTracking/test"
      TEST_SBT_VER: 1.10.7
      SBT_ETC_FILE: $HOME/etc/sbt/sbtopts
      JDK11: adopt@1.11.0-9
      SPARK_LOCAL_IP: "127.0.0.1"
    steps:
    - name: Checkout sbt/sbt
      uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: "${{ matrix.distribution }}"
        java-version: "${{ matrix.java }}"
    - name: Setup SBT
      uses: sbt/setup-sbt@v1
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Coursier cache
      uses: coursier/cache-action@v6
    - name: Cache sbt
      uses: actions/cache@v4
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
    - name: Setup Windows C++ toolchain
      uses: ilammy/msvc-dev-cmd@v1
      if: ${{ matrix.os == 'windows-latest' }}
    - name: Setup WSL2 (Windows Subsystem for Linux)
      uses: vedantmgoyal9/setup-wsl2@main
      if: ${{ matrix.os == 'windows-latest' }}
    # - name: Build and test (9)
    #   if: ${{ matrix.jobtype == 9 }}
    #   shell: bash
    #   run: |
    #     # test building sbtn on Windows
    #     sbt "-Dsbt.io.virtual=false" nativeImage
    #     # smoke test native Image
    #     ./client/target/bin/sbtn --sbt-script=$(pwd)/launcher-package/src/universal/bin/sbt.bat about
    #     ./client/target/bin/sbtn --sbt-script=$(pwd)/launcher-package/src/universal/bin/sbt.bat shutdown
    #     # test launcher script
    #     echo build using JDK 8, test using JDK 8, on Windows
    #     cd launcher-package
    #     bin/coursier.bat resolve
    #     sbt -Dsbt.build.version=$TEST_SBT_VER integrationTest/test
    #     cd citest
    #     ./test.bat
    #     test3/test3.bat
    - name: Test WSL2
      if: ${{ matrix.jobtype == 9 }}
      shell: wsl-run {0}
      run: |
        ls -al
        env
        export PATH=/mnt/c/hostedtoolcache/windows/sbt/1.11.0/sbt/bin:$PATH
        sbt --client about || true
        ls -al /run/user/0/.sbt46911889/ipcsocket/
    - name: Cleanup
      shell: bash
      run: |
        rm -rf "$HOME/.sbt/scripted/" || true
        rm -rf "$HOME/.ivy2/local" || true
        rm -r $(find $HOME/.sbt/boot -name "*-SNAPSHOT") || true
        find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
        find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
        find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
        find $HOME/.sbt                              -name "*.lock"               -delete || true
