# .github/workflows/dependency-graph.yml
name: Submit Dependency Graph
on:
  push:
    branches: [1.12.x, develop]
permissions: {}
jobs:
  submit-graph:
    permissions:
      contents: write # to submit the dependency graph

    name: Submit Dependency Graph
    runs-on: ubuntu-latest # or windows-latest, or macOS-latest
    steps:
      - uses: actions/checkout@v6
      - uses: sbt/setup-sbt@v1
      - uses: scalacenter/sbt-dependency-submission@v3
        with:
          modules-ignore: actions_2.13 command_2.13 main-settings_2.13 main_2.13 run_2.13 sbtroot_2.13 scripted-plugin_2.13 task-system_2.13 tasks_2.13 testing_2.13 zinc-lm-integration_2.13
